#Exercício Python 9: Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.

n = int(input("Digite um número qualquer: "))
print("="*20)
print(n, 'X  1 = ', n * 1)
print(n, 'X  2 = ', n * 2)
print(n, 'X  3 = ', n * 3)
print(n, 'X  4 = ', n * 4)
print(n, 'X  5 = ', n * 5)
print(n, 'X  6 = ', n * 6)
print(n, 'X  7 = ', n * 7)
print(n, 'X  8 = ', n * 8)
print(n, 'X  9 = ', n * 9)
print(n, 'X 10 = ', n * 10)
print('='*20)
print("  ")
print("-"*20)
print('{} X {:2} = {}'.format(n, 1, n*1))
print('{} X {:2} = {}'.format(n, 2, n*2))
print('{} X {:2} = {}'.format(n, 3, n*3))
print('{} X {:2} = {}'.format(n, 4, n*4))
print('{} X {:2} = {}'.format(n, 5, n*5))
print('{} X {:2} = {}'.format(n, 6, n*6))
print('{} X {:2} = {}'.format(n, 7, n*7))
print('{} X {:2} = {}'.format(n, 8, n*8))
print('{} X {:2} = {}'.format(n, 9, n*9))
print('{} X {:2} = {}'.format(n, 10, n*10))
print("-"*20)